version: '3.9'

networks:
    laravel:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: web_server
        ports:
            - "8088:80"
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
        depends_on:
            - mysql
            - php
        networks:
            - laravel
    mysql:
        image: mysql
        container_name: mysql
        ports:
            - "4306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_USER: bagaswihant
            MYSQL_PASSWORD: bagas98
            MYSQL_ROOT_PASSWORD: bagas98
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel
    php:
        image: php:8.2-fpm
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
            
        container_name: php
        volumes:
            - ./src:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - laravel
    mysqlweb:
        image: phpmyadmin/phpmyadmin
        restart: always
        container_name: phpmyadmin
        depends_on:
            - mysql
        ports:
            - "8888:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: bagas98
        networks:
            - laravel

